-- use this file to map the AP item ids to your items
-- first value is the code of the target item and the second is the item type override. The third value is an optional increment multiplier for consumables. (feel free to expand the table with any other values you might need (i.e. special initial values, etc.)!)
-- here are the SM items as an example: https://github.com/Cyb3RGER/sm_ap_tracker/blob/main/scripts/autotracking/item_mapping.lua
BASE_ITEM_ID = 0
ITEM_MAPPING = {
	-- [BASE_ITEM_ID + 00000] = { { "toggle" } },
	-- [BASE_ITEM_ID + 00001] = { { "progressive" } },
	-- [BASE_ITEM_ID + 00002] = { { "consumable" } },
	-- -- handle progressive_toggle as toggle, only changing it's active state
	-- [BASE_ITEM_ID + 00003] = { { "progressive_toggle", "toggle" } },
	-- -- multiple items on this id, add the consumable 3 times
	-- [BASE_ITEM_ID + 00004] = { { "toggle" }, { "consumable", nil, 3 } }
	[0573] = {{"seal1", "toggle"}},
	[0574] = {{"seal2", "toggle"}},
	[0575] = {{"seal3", "toggle"}},
	[0576] = {{"seal4", "toggle"}},
	[0577] = {{"seal5", "toggle"}},

	[0569] = {{"tkey", "toggle"}},
	[1077] = {{"talisman", "toggle"}},
	[0772] = {{"cutall", "toggle"}},
	[1080] = {{"soulring", "toggle"}},

	[1333] = {{"armor", "toggle"}},
	[1396] = {{"ice", "toggle"}},
	[1398] = {{"gembox", "toggle"}},
	[1397] = {{"jump", "toggle"}},
	[1280] = {{"puppet", "toggle"}},
	[1399] = {{"water", "toggle"}},
	[1281] = {{"dio", "toggle"}},
	[1334] = {{"bat", "toggle"}},
	[1282] = {{"mirror", "toggle"}},
	[1400] = {{"zip", "toggle"}},

	[1401] = {{"fastwater", "toggle"}},
	[1402] = {{"fastmud", "toggle"}},

	[1284] = {{"skeleton", "toggle"}},
	[1301] = {{"clown", "toggle"}},
	[1286] = {{"axe", "toggle"}},
	[1310] = {{"ukoback", "toggle"}},

	[1292] = {{"food", "toggle"}},
	[1296] = {{"yell", "toggle"}},
	[1297] = {{"shock", "toggle"}},

	[1382] = {{"drydk", "toggle"}},
	[1355] = {{"bark", "toggle"}},
	[1335] = {{"panther", "toggle"}},
	[1283] = {{"imp", "toggle"}}

	-- [None] = {{"moat", "toggle"}}
	-- [None] = {{"aguni", "toggle"}}
	-- [None] = {{"dark", "toggle"}}

	-- [1285] = {{"Zombie Soul", "toggle"}},
	-- [1287] = {{"Student Witch Soul", "toggle"}},
	-- [1288] = {{"Warg Soul", "toggle"}},
	-- [1289] = {{"Bomber Armor Soul", "toggle"}},
	-- [1290] = {{"Amalaric Sniper Soul", "toggle"}},
	-- [1291] = {{"Cave Troll Soul", "toggle"}},
	-- [1293] = {{"Slime Soul", "toggle"}},
	-- [1294] = {{"Yorick Soul", "toggle"}},
	-- [1295] = {{"Une Soul", "toggle"}},
	-- [1298] = {{"Fleaman Soul", "toggle"}},
	-- [1299] = {{"Ripper Soul", "toggle"}},
	-- [1300] = {{"Guillotiner Soul", "toggle"}},
	-- [1302] = {{"Malachi Soul", "toggle"}},
	-- [1303] = {{"Disc Armor Soul", "toggle"}},
	-- [1304] = {{"Great Axe Armor Soul", "toggle"}},
	-- [1305] = {{"Slaughterer Soul", "toggle"}},
	-- [1306] = {{"Hell Boar Soul", "toggle"}},
	-- [1307] = {{"Frozen Shade Soul", "toggle"}},
	-- [1308] = {{"Merman Soul", "toggle"}},
	-- [1309] = {{"Larva Soul", "toggle"}},
	-- [1311] = {{"Decarabia Soul", "toggle"}},
	-- [1312] = {{"Succubus Soul", "toggle"}},
	-- [1313] = {{"Slogra Soul", "toggle"}},
	-- [1314] = {{"Erinys Soul", "toggle"}},
	-- [1315] = {{"Homunculus Soul", "toggle"}},
	-- [1316] = {{"Witch Soul", "toggle"}},
	-- [1317] = {{"Fish Head Soul", "toggle"}},
	-- [1318] = {{"Mollusca Soul", "toggle"}},
	-- [1319] = {{"Dead Mate Soul", "toggle"}},
	-- [1320] = {{"Killer Fish Soul", "toggle"}},
	-- [1321] = {{"Malacoda Soul", "toggle"}},
	-- [1322] = {{"Flame Demon Soul", "toggle"}},
	-- [1323] = {{"Aguni Soul", "toggle"}},
	-- [1324] = {{"Abaddon Soul", "toggle"}},
	-- [1336] = {{"Armor Knight Soul", "toggle"}},
	-- [1337] = {{"Spin Devil Soul", "toggle"}},
	-- [1338] = {{"Skull Archer Soul", "toggle"}},
	-- [1339] = {{"Ghost Soul", "toggle"}},
	-- [1340] = {{"Yeti Soul", "toggle"}},
	-- [1341] = {{"Buer Soul", "toggle"}},
	-- [1342] = {{"Manticore Soul", "toggle"}},
	-- [1343] = {{"Mushussu Soul", "toggle"}},
	-- [1344] = {{"White Dragon Soul", "toggle"}},
	-- [1345] = {{"Catoblepas Soul", "toggle"}},
	-- [1346] = {{"Gorgon Soul", "toggle"}},
	-- [1347] = {{"Persephone Soul", "toggle"}},
	-- [1348] = {{"Flying Humanoid Soul", "toggle"}},
	-- [1349] = {{"Devil Soul", "toggle"}},
	-- [1350] = {{"Medusa Head Soul", "toggle"}},
	-- [1351] = {{"Final Guard Soul", "toggle"}},
	-- [1352] = {{"Werewolf Soul", "toggle"}},
	-- [1353] = {{"Alura Une Soul", "toggle"}},
	-- [1354] = {{"Iron Golem Soul", "toggle"}},
	-- [1356] = {{"Barbariccia Soul", "toggle"}},
	-- [1357] = {{"Valkyrie Soul", "toggle"}},
	-- [1358] = {{"Bat Soul", "toggle"}},
	-- [1359] = {{"Great Armor Soul", "toggle"}},
	-- [1360] = {{"Mini Devil Soul", "toggle"}},
	-- [1361] = {{"Harpy Soul", "toggle"}},
	-- [1362] = {{"Corpseweed Soul", "toggle"}},
	-- [1363] = {{"Quetzalcoatl Soul", "toggle"}},
	-- [1364] = {{"Needles Soul", "toggle"}},
	-- [1365] = {{"Alastor Soul", "toggle"}},
	-- [1366] = {{"Gaibon Soul", "toggle"}},
	-- [1367] = {{"Gergoth Soul", "toggle"}},
	-- [1368] = {{"Death Soul", "toggle"}},
	-- [1369] = {{"Golem Soul", "toggle"}},
	-- [1370] = {{"Bone Pillar Soul", "toggle"}},
	-- [1371] = {{"Lilith Soul", "toggle"}},
	-- [1372] = {{"Ghost Dancer Soul", "toggle"}},
	-- [1373] = {{"Tanjelly Soul", "toggle"}},
	-- [1374] = {{"Bugbear Soul", "toggle"}},
	-- [1375] = {{"Arc Demon Soul", "toggle"}},
	-- [1376] = {{"Giant Slug Soul", "toggle"}},
	-- [1377] = {{"Killer Doll Soul", "toggle"}},
	-- [1378] = {{"Tombstone Soul", "toggle"}},
	-- [1379] = {{"Treant Soul", "toggle"}},
	-- [1380] = {{"Ghoul Soul", "toggle"}},
	-- [1381] = {{"Skelerang Soul", "toggle"}},
	-- [1383] = {{"Dead Warrior Soul", "toggle"}},
	-- [1384] = {{"Dead Pirate Soul", "toggle"}},
	-- [1385] = {{"Draghignazzo Soul", "toggle"}},
	-- [1386] = {{"Heart Eater Soul", "toggle"}},
	-- [1387] = {{"Peeping Eye Soul", "toggle"}},
	-- [1388] = {{"Skeleton Farmer Soul", "toggle"}},
	-- [1389] = {{"The Creature Soul", "toggle"}},
	-- [1390] = {{"Mimic Soul", "toggle"}},
	-- [1391] = {{"Mothman Soul", "toggle"}},
	-- [1392] = {{"Ouija Table Soul", "toggle"}},
	-- [1393] = {{"Dead Crusader Soul", "toggle"}},
	-- [1394] = {{"Stolas Soul", "toggle"}},
	-- [1395] = {{"Wakwak Tree Soul", "toggle"}},
}
