ScriptHost:LoadScript("scripts/autotracking/souls_by_region_codes.lua")
BASE_LOCATION_ID = 0
LOCATION_MAPPING = {
	-- [BASE_LOCATION_ID + 00001] = { { "@Example Parent/Example Location 1/Example Section 1" } },
	-- [BASE_LOCATION_ID + 00002] = { { "toggle" } },
	-- -- multiple locations on this id
	-- [BASE_LOCATION_ID + 00003] = { { "@Example Parent/Example Location 1/Example Section 1" }, { "@Example Parent/Example Location 1/Example Section 2" } },
	[BASE_LOCATION_ID + 044] = {{"@The Lost Village/Above Entrance/"}},
	[BASE_LOCATION_ID + 011] = {{"@The Lost Village/Upper Big Room Corner/"}},
	[BASE_LOCATION_ID + 105] = {{"@The Lost Village/Pre-Boss Room Upper/"}},
	[BASE_LOCATION_ID + 006] = {{"@The Lost Village/Pre-Boss Room Lower/"}},
	[BASE_LOCATION_ID + 078] = {{"@The Lost Village/Drawbridge Room/"}},
	[BASE_LOCATION_ID + 081] = {{"@The Lost Village/Above Drawbridge/"}},
	[BASE_LOCATION_ID + 093] = {{"@The Lost Village/In Moat/"}},
	[BASE_LOCATION_ID + 309] = {{"@The Lost Village/Flying Armor Soul/"}},
	[BASE_LOCATION_ID + 108] = {{"@The Lost Village/Flying Armor Indoor Room/"}},
	[BASE_LOCATION_ID + 103] = {{"@The Lost Village/West Plaza/"}},
	[BASE_LOCATION_ID + 111] = {{"@The Lost Village/West Building Upper/"}},
	[BASE_LOCATION_ID + 031] = {{"@The Lost Village/West Building Lower/"}},
	[BASE_LOCATION_ID + 032] = {{"@The Lost Village/Central Building/"}},
	[BASE_LOCATION_ID + 007] = {{"@The Lost Village/East Plaza/"}},
	[BASE_LOCATION_ID + 033] = {{"@The Lost Village/Hidden Floor Room/Item 1"}},
	[BASE_LOCATION_ID + 043] = {{"@The Lost Village/Hidden Floor Room/Item 2"}},
	[BASE_LOCATION_ID + 079] = {{"@The Lost Village/Mirror Room Left/"}},
	[BASE_LOCATION_ID + 096] = {{"@The Lost Village/Mirror Room Right/"}},
	[BASE_LOCATION_ID + 041] = {{"@The Lost Village/Axe Armor Hallway/"}},
	[BASE_LOCATION_ID + 087] = {{"@The Lost Village/Underground Shaft/"}},
	[BASE_LOCATION_ID + 083] = {{"@The Lost Village/Above Guest House Entrance/"}},

	[BASE_LOCATION_ID + 112] = {{"@Wizardry Lab/Mirror Room/Outside Mirror"}},
	[BASE_LOCATION_ID + 084] = {{"@Wizardry Lab/Mirror Room/Mirror World"}},
	[BASE_LOCATION_ID + 019] = {{"@Wizardry Lab/Main Entry Shaft/"}},
	[BASE_LOCATION_ID + 120] = {{"@Wizardry Lab/Upper Big Room/"}},
	[BASE_LOCATION_ID + 085] = {{"@Wizardry Lab/West Gate/"}},
	[BASE_LOCATION_ID + 062] = {{"@Wizardry Lab/Behind West Gate/Item"}},
	[BASE_LOCATION_ID + 512] = {{"@Wizardry Lab/Behind West Gate/Button"}},
	[BASE_LOCATION_ID + 040] = {{"@Wizardry Lab/Ceiling Secret Room/"}},
	[BASE_LOCATION_ID + 372] = {{"@Wizardry Lab/Balore Soul/"}},
	[BASE_LOCATION_ID + 076] = {{"@Wizardry Lab/East Gate/Item"}},
	[BASE_LOCATION_ID + 513] = {{"@Wizardry Lab/East Gate/Button"}},
	[BASE_LOCATION_ID + 101] = {{"@Wizardry Lab/Money Gate/"}},
	[BASE_LOCATION_ID + 094] = {{"@Wizardry Lab/Underwater Left/"}},
	[BASE_LOCATION_ID + 016] = {{"@Wizardry Lab/Underwater Right/"}},
	[BASE_LOCATION_ID + 077] = {{"@Wizardry Lab/Above Water/"}},

	[BASE_LOCATION_ID + 002] = {{"@Garden of Madness/Lower Tree Hallway/"}},
	[BASE_LOCATION_ID + 063] = {{"@Garden of Madness/West Big Room/"}},
	[BASE_LOCATION_ID + 114] = {{"@Garden of Madness/West Big Room Alcove/"}},
	[BASE_LOCATION_ID + 075] = {{"@Garden of Madness/West Upper Room/"}},
	[BASE_LOCATION_ID + 068] = {{"@Garden of Madness/Hidden Room/"}},
	[BASE_LOCATION_ID + 009] = {{"@Garden of Madness/Center Room/"}},
	[BASE_LOCATION_ID + 069] = {{"@Garden of Madness/Money Gate/"}},
	[BASE_LOCATION_ID + 115] = {{"@Garden of Madness/Underground Room/"}},
	[BASE_LOCATION_ID + 117] = {{"@Garden of Madness/East Alcove/"}},
	[BASE_LOCATION_ID + 514] = {{"@Garden of Madness/Gate Button/"}},

	[BASE_LOCATION_ID + 099] = {{"@Demon Guest House/Secret Room/"}},
	[BASE_LOCATION_ID + 001] = {{"@Demon Guest House/Antechamber/"}},
	[BASE_LOCATION_ID + 034] = {{"@Demon Guest House/Lower Main Chamber Bottom Room/"}},
	[BASE_LOCATION_ID + 021] = {{"@Demon Guest House/Puppet Hole/"}},
	[BASE_LOCATION_ID + 104] = {{"@Demon Guest House/Number 1 Room/"}},
	[BASE_LOCATION_ID + 113] = {{"@Demon Guest House/Number 5 Room/"}},
	[BASE_LOCATION_ID + 091] = {{"@Demon Guest House/Number 8 Room/"}},
	[BASE_LOCATION_ID + 070] = {{"@Demon Guest House/Number 9 Room/"}},
	[BASE_LOCATION_ID + 109] = {{"@Demon Guest House/Number 12 Room/"}},
	[BASE_LOCATION_ID + 074] = {{"@Demon Guest House/Mirror Room/Mirror World"}},
	[BASE_LOCATION_ID + 064] = {{"@Demon Guest House/Mirror Room/Outside Mirror"}},
	[BASE_LOCATION_ID + 012] = {{"@Demon Guest House/Doll Alcove/"}},
	[BASE_LOCATION_ID + 003] = {{"@Demon Guest House/West Wing Left/"}},
	[BASE_LOCATION_ID + 057] = {{"@Demon Guest House/West Wing Right/"}},
	[BASE_LOCATION_ID + 256] = {{"@Demon Guest House/Puppet Master Soul/"}},
	[BASE_LOCATION_ID + 072] = {{"@Demon Guest House/Ice Block Room Left/"}},
	[BASE_LOCATION_ID + 059] = {{"@Demon Guest House/Ice Block Room Right/"}},
	[BASE_LOCATION_ID + 046] = {{"@Demon Guest House/Central Main Chamber Bottom Room/"}},
	[BASE_LOCATION_ID + 055] = {{"@Demon Guest House/Central Main Chamber Middle Room/"}},
	[BASE_LOCATION_ID + 037] = {{"@Demon Guest House/Central Main Chamber Top Room/"}},
	[BASE_LOCATION_ID + 258] = {{"@Demon Guest House/Paranoia Soul/"}},
	[BASE_LOCATION_ID + 073] = {{"@Demon Guest House/Beyond Paranoia/"}},
	[BASE_LOCATION_ID + 054] = {{"@Demon Guest House/Paranoia Mirror/"}},

	[BASE_LOCATION_ID + 106] = {{"@The Dark Chapel/Entrance Alcove/"}},
	[BASE_LOCATION_ID + 035] = {{"@The Dark Chapel/Catacombs Top Left/"}},
	[BASE_LOCATION_ID + 080] = {{"@The Dark Chapel/Catacombs Middle Room/"}},
	[BASE_LOCATION_ID + 118] = {{"@The Dark Chapel/Catacombs Soul Barrier/"}},
	[BASE_LOCATION_ID + 086] = {{"@The Dark Chapel/Catacombs Mirror Room/Outside Mirror"}},
	[BASE_LOCATION_ID + 089] = {{"@The Dark Chapel/Catacombs Mirror Room/Mirror World"}},
	[BASE_LOCATION_ID + 088] = {{"@The Dark Chapel/Big Square Room Alcove/"}},
	[BASE_LOCATION_ID + 008] = {{"@The Dark Chapel/Main Room/"}},
	[BASE_LOCATION_ID + 047] = {{"@The Dark Chapel/Bell Room In Bell/"}},
	[BASE_LOCATION_ID + 026] = {{"@The Dark Chapel/Bell Room Top Left/"}},
	[BASE_LOCATION_ID + 022] = {{"@The Dark Chapel/Bell Room Right/"}},
	[BASE_LOCATION_ID + 090] = {{"@The Dark Chapel/Post-Dmitrii Room/"}},
	[BASE_LOCATION_ID + 373] = {{"@The Dark Chapel/Malphas Soul/"}},
	[BASE_LOCATION_ID + 121] = {{"@The Dark Chapel/Big Room Top Right/"}},
	[BASE_LOCATION_ID + 060] = {{"@The Dark Chapel/Big Room Central/"}},
	[BASE_LOCATION_ID + 013] = {{"@The Dark Chapel/Big Room Lower/"}},

	[BASE_LOCATION_ID + 053] = {{"@Condemned Tower/1F West/"}},
	[BASE_LOCATION_ID + 018] = {{"@Condemned Tower/1F East/"}},
	[BASE_LOCATION_ID + 092] = {{"@Condemned Tower/2F East/"}},
	[BASE_LOCATION_ID + 116] = {{"@Condemned Tower/5F West/"}},
	[BASE_LOCATION_ID + 058] = {{"@Condemned Tower/7F West/"}},
	[BASE_LOCATION_ID + 030] = {{"@Condemned Tower/Top of the Tower/"}},
	[BASE_LOCATION_ID + 343] = {{"@Condemned Tower/Gergoth Soul/"}},

	[BASE_LOCATION_ID + 100] = {{"@Cursed Clock Tower/Money Gate/"}},
	[BASE_LOCATION_ID + 071] = {{"@Cursed Clock Tower/Lower Corner Room/"}},
	[BASE_LOCATION_ID + 065] = {{"@Cursed Clock Tower/Mirror Room/Outside Mirror"}},
	[BASE_LOCATION_ID + 095] = {{"@Cursed Clock Tower/Mirror Room/Mirror World"}},
	[BASE_LOCATION_ID + 004] = {{"@Cursed Clock Tower/Bugbear Hallway/"}},
	[BASE_LOCATION_ID + 061] = {{"@Cursed Clock Tower/East Gear Room/"}},
	[BASE_LOCATION_ID + 045] = {{"@Cursed Clock Tower/Spike Room Secret/"}},
	[BASE_LOCATION_ID + 257] = {{"@Cursed Clock Tower/Zephyr Soul/"}},

	[BASE_LOCATION_ID + 375] = {{"@Subterranean Hell/Rahab Soul/"}},
	[BASE_LOCATION_ID + 023] = {{"@Subterranean Hell/Giant Underwater Room Center Left/"}},
	[BASE_LOCATION_ID + 038] = {{"@Subterranean Hell/Giant Underwater Room Center Right/"}},
	[BASE_LOCATION_ID + 066] = {{"@Subterranean Hell/Giant Underwater Room Top Left/"}},
	[BASE_LOCATION_ID + 052] = {{"@Subterranean Hell/Giant Underwater Room Bottom Right/"}},
	[BASE_LOCATION_ID + 056] = {{"@Subterranean Hell/Near Save Room/"}},
	[BASE_LOCATION_ID + 050] = {{"@Subterranean Hell/Central Lower Room/"}},
	[BASE_LOCATION_ID + 039] = {{"@Subterranean Hell/Central Upper Room/"}},
	[BASE_LOCATION_ID + 067] = {{"@Subterranean Hell/Behind Waterfall/"}},
	[BASE_LOCATION_ID + 049] = {{"@Subterranean Hell/Waterfall Room Lower/"}},
	[BASE_LOCATION_ID + 051] = {{"@Subterranean Hell/Waterfall Room Middle/"}},
	[BASE_LOCATION_ID + 048] = {{"@Subterranean Hell/Waterfall Room Upper/"}},
	[BASE_LOCATION_ID + 515] = {{"@Subterranean Hell/Gate Button/"}},

	[BASE_LOCATION_ID + 098] = {{"@Silenced Ruins/Ice Block Room/"}},
	[BASE_LOCATION_ID + 310] = {{"@Silenced Ruins/Bat Company Soul/"}},
	[BASE_LOCATION_ID + 024] = {{"@Silenced Ruins/Mirror Room/Outside Mirror"}},
	[BASE_LOCATION_ID + 015] = {{"@Silenced Ruins/Mirror Room/Mirror World"}},

	[BASE_LOCATION_ID + 042] = {{"@The Pinnacle/Lower Hidden Room/"}},
	[BASE_LOCATION_ID + 110] = {{"@The Pinnacle/Under Big Staircase/"}},
	[BASE_LOCATION_ID + 025] = {{"@The Pinnacle/Central Indoor Room/"}},
	[BASE_LOCATION_ID + 119] = {{"@The Pinnacle/Central Outdoor Room/"}},
	[BASE_LOCATION_ID + 097] = {{"@The Pinnacle/Before Throne Room Secret Left/"}},
	[BASE_LOCATION_ID + 107] = {{"@The Pinnacle/Before Throne Room Secret Right/"}},
	[BASE_LOCATION_ID + 005] = {{"@The Pinnacle/Beyond Throne Room/"}},
	[BASE_LOCATION_ID + 299] = {{"@The Pinnacle/Aguni Soul/"}},

	[BASE_LOCATION_ID + 344] = {{"@Mine of Judgment/Death Soul/"}},

	[BASE_LOCATION_ID + 020] = {{"@The Abyss/Sand Area/"}},
	[BASE_LOCATION_ID + 102] = {{"@The Abyss/Ice Area/"}},
	[BASE_LOCATION_ID + 300] = {{"@The Abyss/Abaddon Soul/"}},

	[BASE_LOCATION_ID + 259] = {{"@Soulsanity/Uncommon Souls/Imp Soul/"}},
	[BASE_LOCATION_ID + 260] = {{"@Soulsanity/Uncommon Souls/Skeleton Soul/"}},
	[BASE_LOCATION_ID + 261] = {{"@Soulsanity/Uncommon Souls/Zombie Soul/"}},
	[BASE_LOCATION_ID + 262] = {{"@Soulsanity/Common Souls/Axe Armor Soul/"}},
	[BASE_LOCATION_ID + 263] = {{"@Soulsanity/Uncommon Souls/Student Witch Soul/"}},
	[BASE_LOCATION_ID + 264] = {{"@Soulsanity/Common Souls/Warg Soul/"}},
	[BASE_LOCATION_ID + 265] = {{"@Soulsanity/Uncommon Souls/Bomber Armor Soul/"}},
	[BASE_LOCATION_ID + 266] = {{"@Soulsanity/Uncommon Souls/Amalaric Sniper Soul/"}},
	[BASE_LOCATION_ID + 267] = {{"@Soulsanity/Common Souls/Cave Troll Soul/"}},
	[BASE_LOCATION_ID + 268] = {{"@Soulsanity/Uncommon Souls/Waiter Skeleton Soul/"}},
	[BASE_LOCATION_ID + 269] = {{"@Soulsanity/Common Souls/Slime Soul/"}},
	[BASE_LOCATION_ID + 270] = {{"@Soulsanity/Uncommon Souls/Yorick Soul/"}},
	[BASE_LOCATION_ID + 271] = {{"@Soulsanity/Uncommon Souls/Une Soul/"}},
	[BASE_LOCATION_ID + 272] = {{"@Soulsanity/Uncommon Souls/Mandragora Soul/"}},
	[BASE_LOCATION_ID + 273] = {{"@Soulsanity/Uncommon Souls/Rycuda Soul/"}},
	[BASE_LOCATION_ID + 274] = {{"@Soulsanity/Uncommon Souls/Fleaman Soul/"}},
	[BASE_LOCATION_ID + 275] = {{"@Soulsanity/Uncommon Souls/Ripper Soul/"}},
	[BASE_LOCATION_ID + 276] = {{"@Soulsanity/Common Souls/Guillotiner Soul/"}},
	[BASE_LOCATION_ID + 277] = {{"@Soulsanity/Uncommon Souls/Killer Clown Soul/"}},
	[BASE_LOCATION_ID + 278] = {{"@Soulsanity/Uncommon Souls/Malachi Soul/"}},
	[BASE_LOCATION_ID + 279] = {{"@Soulsanity/Uncommon Souls/Disc Armor Soul/"}},
	[BASE_LOCATION_ID + 280] = {{"@Soulsanity/Rare Souls/Great Axe Armor Soul/"}},
	[BASE_LOCATION_ID + 281] = {{"@Soulsanity/Uncommon Souls/Slaughterer Soul/"}},
	[BASE_LOCATION_ID + 282] = {{"@Soulsanity/Uncommon Souls/Hell Boar Soul/"}},
	[BASE_LOCATION_ID + 283] = {{"@Soulsanity/Uncommon Souls/Frozen Shade Soul/"}},
	[BASE_LOCATION_ID + 284] = {{"@Soulsanity/Common Souls/Merman Soul/"}},
	[BASE_LOCATION_ID + 285] = {{"@Soulsanity/Uncommon Souls/Larva Soul/"}},
	[BASE_LOCATION_ID + 286] = {{"@Soulsanity/Uncommon Souls/Ukoback Soul/"}},
	[BASE_LOCATION_ID + 287] = {{"@Soulsanity/Common Souls/Decarabia Soul/"}},
	[BASE_LOCATION_ID + 288] = {{"@Soulsanity/Uncommon Souls/Succubus Soul/"}},
	[BASE_LOCATION_ID + 289] = {{"@Soulsanity/Common Souls/Slogra Soul/"}},
	[BASE_LOCATION_ID + 290] = {{"@Soulsanity/Rare Souls/Erinys Soul/"}},
	[BASE_LOCATION_ID + 291] = {{"@Soulsanity/Common Souls/Homunculus Soul/"}},
	[BASE_LOCATION_ID + 292] = {{"@Soulsanity/Uncommon Souls/Witch Soul/"}},
	[BASE_LOCATION_ID + 293] = {{"@Soulsanity/Uncommon Souls/Fish Head Soul/"}},
	[BASE_LOCATION_ID + 294] = {{"@Soulsanity/Uncommon Souls/Mollusca Soul/"}},
	[BASE_LOCATION_ID + 295] = {{"@Soulsanity/Common Souls/Dead Mate Soul/"}},
	[BASE_LOCATION_ID + 296] = {{"@Soulsanity/Uncommon Souls/Killer Fish Soul/"}},
	[BASE_LOCATION_ID + 297] = {{"@Soulsanity/Uncommon Souls/Malacoda Soul/"}},
	[BASE_LOCATION_ID + 298] = {{"@Soulsanity/Uncommon Souls/Flame Demon Soul/"}},
	[BASE_LOCATION_ID + 311] = {{"@Soulsanity/Common Souls/Black Panther Soul/"}},
	[BASE_LOCATION_ID + 312] = {{"@Soulsanity/Uncommon Souls/Armor Knight Soul/"}},
	[BASE_LOCATION_ID + 313] = {{"@Soulsanity/Common Souls/Spin Devil Soul/"}},
	[BASE_LOCATION_ID + 314] = {{"@Soulsanity/Uncommon Souls/Skull Archer Soul/"}},
	[BASE_LOCATION_ID + 315] = {{"@Soulsanity/Rare Souls/Ghost Soul/"}},
	[BASE_LOCATION_ID + 316] = {{"@Soulsanity/Common Souls/Yeti Soul/"}},
	[BASE_LOCATION_ID + 317] = {{"@Soulsanity/Common Souls/Buer Soul/"}},
	[BASE_LOCATION_ID + 318] = {{"@Soulsanity/Uncommon Souls/Manticore Soul/"}},
	[BASE_LOCATION_ID + 319] = {{"@Soulsanity/Uncommon Souls/Mushussu Soul/"}},
	[BASE_LOCATION_ID + 320] = {{"@Soulsanity/Uncommon Souls/White Dragon Soul/"}},
	[BASE_LOCATION_ID + 321] = {{"@Soulsanity/Uncommon Souls/Catoblepas Soul/"}},
	[BASE_LOCATION_ID + 322] = {{"@Soulsanity/Rare Souls/Gorgon Soul/"}},
	[BASE_LOCATION_ID + 323] = {{"@Soulsanity/Uncommon Souls/Persephone Soul/"}},
	[BASE_LOCATION_ID + 324] = {{"@Soulsanity/Common Souls/Flying Humanoid Soul/"}},
	[BASE_LOCATION_ID + 325] = {{"@Soulsanity/Uncommon Souls/Devil Soul/"}},
	[BASE_LOCATION_ID + 326] = {{"@Soulsanity/Rare Souls/Medusa Head Soul/"}},
	[BASE_LOCATION_ID + 327] = {{"@Soulsanity/Rare Souls/Final Guard Soul/"}},
	[BASE_LOCATION_ID + 328] = {{"@Soulsanity/Uncommon Souls/Werewolf Soul/"}},
	[BASE_LOCATION_ID + 329] = {{"@Soulsanity/Uncommon Souls/Alura Une Soul/"}},
	[BASE_LOCATION_ID + 330] = {{"@Soulsanity/Rare Souls/Iron Golem Soul/"}},
	[BASE_LOCATION_ID + 331] = {{"@Soulsanity/Rare Souls/Bone Ark Soul/"}},
	[BASE_LOCATION_ID + 332] = {{"@Soulsanity/Rare Souls/Barbariccia Soul/"}},
	[BASE_LOCATION_ID + 333] = {{"@Soulsanity/Rare Souls/Valkyrie Soul/"}},
	[BASE_LOCATION_ID + 334] = {{"@Soulsanity/Uncommon Souls/Bat Soul/"}},
	[BASE_LOCATION_ID + 335] = {{"@Soulsanity/Uncommon Souls/Great Armor Soul/"}},
	[BASE_LOCATION_ID + 336] = {{"@Soulsanity/Uncommon Souls/Mini Devil Soul/"}},
	[BASE_LOCATION_ID + 337] = {{"@Soulsanity/Uncommon Souls/Harpy Soul/"}},
	[BASE_LOCATION_ID + 338] = {{"@Soulsanity/Common Souls/Corpseweed Soul/"}},
	[BASE_LOCATION_ID + 339] = {{"@Soulsanity/Uncommon Souls/Quetzalcoatl Soul/"}},
	[BASE_LOCATION_ID + 340] = {{"@Soulsanity/Uncommon Souls/Needles Soul/"}},
	[BASE_LOCATION_ID + 341] = {{"@Soulsanity/Uncommon Souls/Alastor Soul/"}},
	[BASE_LOCATION_ID + 342] = {{"@Soulsanity/Uncommon Souls/Gaibon Soul/"}},
	[BASE_LOCATION_ID + 345] = {{"@Soulsanity/Uncommon Souls/Golem Soul/"}},
	[BASE_LOCATION_ID + 346] = {{"@Soulsanity/Rare Souls/Bone Pillar Soul/"}},
	[BASE_LOCATION_ID + 347] = {{"@Soulsanity/Uncommon Souls/Lilith Soul/"}},
	[BASE_LOCATION_ID + 348] = {{"@Soulsanity/Uncommon Souls/Ghost Dancer Soul/"}},
	[BASE_LOCATION_ID + 349] = {{"@Soulsanity/Rare Souls/Tanjelly Soul/"}},
	[BASE_LOCATION_ID + 350] = {{"@Soulsanity/Rare Souls/Bugbear Soul/"}},
	[BASE_LOCATION_ID + 351] = {{"@Soulsanity/Rare Souls/Arc Demon Soul/"}},
	[BASE_LOCATION_ID + 352] = {{"@Soulsanity/Rare Souls/Giant Slug Soul/"}},
	[BASE_LOCATION_ID + 353] = {{"@Soulsanity/Rare Souls/Killer Doll Soul/"}},
	[BASE_LOCATION_ID + 354] = {{"@Soulsanity/Rare Souls/Tombstone Soul/"}},
	[BASE_LOCATION_ID + 355] = {{"@Soulsanity/Rare Souls/Treant Soul/"}},
	[BASE_LOCATION_ID + 356] = {{"@Soulsanity/Rare Souls/Ghoul Soul/"}},
	[BASE_LOCATION_ID + 357] = {{"@Soulsanity/Uncommon Souls/Skelerang Soul/"}},
	[BASE_LOCATION_ID + 358] = {{"@Soulsanity/Rare Souls/Skeleton Ape Soul/"}},
	[BASE_LOCATION_ID + 359] = {{"@Soulsanity/Rare Souls/Dead Warrior Soul/"}},
	[BASE_LOCATION_ID + 360] = {{"@Soulsanity/Uncommon Souls/Dead Pirate Soul/"}},
	[BASE_LOCATION_ID + 361] = {{"@Soulsanity/Rare Souls/Draghignazzo Soul/"}},
	[BASE_LOCATION_ID + 362] = {{"@Soulsanity/Rare Souls/Heart Eater Soul/"}},
	[BASE_LOCATION_ID + 363] = {{"@Soulsanity/Rare Souls/Peeping Eye Soul/"}},
	[BASE_LOCATION_ID + 364] = {{"@Soulsanity/Rare Souls/Skeleton Farmer Soul/"}},
	[BASE_LOCATION_ID + 365] = {{"@Soulsanity/Rare Souls/The Creature Soul/"}},
	[BASE_LOCATION_ID + 366] = {{"@Soulsanity/Rare Souls/Mimic Soul/"}},
	[BASE_LOCATION_ID + 367] = {{"@Soulsanity/Common Souls/Mothman Soul/"}},
	[BASE_LOCATION_ID + 368] = {{"@Soulsanity/Rare Souls/Ouija Table Soul/"}},
	[BASE_LOCATION_ID + 369] = {{"@Soulsanity/Rare Souls/Dead Crusader Soul/"}},
	[BASE_LOCATION_ID + 370] = {{"@Soulsanity/Rare Souls/Stolas Soul/"}},
	[BASE_LOCATION_ID + 371] = {{"@Soulsanity/Uncommon Souls/Wakwak Tree Soul/"}},
	[BASE_LOCATION_ID + 377] = {{"@Soulsanity/Rare Souls/Procel Soul/"}},
	[BASE_LOCATION_ID + 378] = {{"@Soulsanity/Uncommon Souls/Mud Demon Soul/"}}
}

-- Apply all of the junk from souls by region codes to the corresponding soulsanity entry
for loc_id, loc_table in pairs(LOCATION_MAPPING) do
	for i = #loc_table, 1, -1 do
		loc = loc_table[i]
        if loc[1]:sub(1, 11) == "@Soulsanity" then
            local section = loc[1]:sub(1, -2):match("([^/]+)$")
            for _, code in ipairs(SOULSBYREGIONCODES) do
                if code[1]:match("([^/]+)$") == section then
                    table.insert(
						LOCATION_MAPPING[loc_id], code
					)
                end
            end
        end
    end
end