-- use this file to map the AP location ids to your locations
-- first value is the code of the target location/item and the second is the item type override (feel free to expand the table with any other values you might need (i.e. special initial values, increments, etc.)!)
-- to reference a location in Pop use @ in the beginning and then path to the section (more info: https://github.com/black-sliver/PopTracker/blob/master/doc/PACKS.md#locations)
-- to reference an item use it's code
-- here are the SM locations as an example: https://github.com/Cyb3RGER/sm_ap_tracker/blob/main/scripts/autotracking/location_mapping.lua
BASE_LOCATION_ID = 0
LOCATION_MAPPING = {
	-- [BASE_LOCATION_ID + 00001] = { { "@Example Parent/Example Location 1/Example Section 1" } },
	-- [BASE_LOCATION_ID + 00002] = { { "toggle" } },
	-- -- multiple locations on this id
	-- [BASE_LOCATION_ID + 00003] = { { "@Example Parent/Example Location 1/Example Section 1" }, { "@Example Parent/Example Location 1/Example Section 2" } },
	[00001] = {{"@The Lost Village/Above Entrance/"}},
	[00002] = {{"@The Lost Village/Upper Big Room Corner/"}},
	[00003] = {{"@The Lost Village/Pre-Boss Room Upper/"}},
	[00004] = {{"@The Lost Village/Pre-Boss Room Lower/"}},
	[00005] = {{"@The Lost Village/Drawbridge Room/"}},
	[00006] = {{"@The Lost Village/Above Drawbridge/"}},
	[00007] = {{"@The Lost Village/In Moat/"}},
	[00008] = {{"@The Lost Village/Flying Armor Soul/"}},
	[00009] = {{"@The Lost Village/Flying Armor Indoor Room/"}},
	[00010] = {{"@The Lost Village/West Plaza/"}},
	[00011] = {{"@The Lost Village/West Building Upper/"}},
	[00012] = {{"@The Lost Village/West Building Lower/"}},
	[00013] = {{"@The Lost Village/Central Building/"}},
	[00014] = {{"@The Lost Village/East Plaza/"}},
	[00015] = {{"@The Lost Village/Hidden Floor Room 1/"}},
	[00016] = {{"@The Lost Village/Hidden Floor Room 2/"}},
	[00017] = {{"@The Lost Village/Mirror Room Left/"}},
	[00018] = {{"@The Lost Village/Mirror Room Right/"}},
	[00019] = {{"@The Lost Village/Axe Armor Hallway/"}},
	[00020] = {{"@The Lost Village/Underground Shaft/"}},
	[00021] = {{"@The Lost Village/Above Guest House Entrance/"}},

	[00022] = {{"@Wizardry Lab/Mirror Room/"}},
	[00023] = {{"@Wizardry Lab/Mirror World/"}},
	[00024] = {{"@Wizardry Lab/Main Entry Shaft/"}},
	[00025] = {{"@Wizardry Lab/Upper Big Room/"}},
	[00026] = {{"@Wizardry Lab/West Gate/"}},
	[00027] = {{"@Wizardry Lab/Behind West Gate/"}},
	[00028] = {{"@Wizardry Lab/Ceiling Secret Room/"}},
	[00029] = {{"@Wizardry Lab/Balore Soul/"}},
	[00030] = {{"@Wizardry Lab/East Gate/"}},
	[00031] = {{"@Wizardry Lab/Money Gate/"}},
	[00032] = {{"@Wizardry Lab/Underwater Left/"}},
	[00033] = {{"@Wizardry Lab/Underwater Right/"}},
	[00034] = {{"@Wizardry Lab/Above Water/"}},

	[00035] = {{"@Garden of Madness/Lower Tree Hallway/"}},
	[00036] = {{"@Garden of Madness/West Big Room/"}},
	[00037] = {{"@Garden of Madness/West Big Room Alcove/"}},
	[00038] = {{"@Garden of Madness/West Upper Room/"}},
	[00039] = {{"@Garden of Madness/Hidden Room/"}},
	[00040] = {{"@Garden of Madness/Center Room/"}},
	[00041] = {{"@Garden of Madness/Money Gate/"}},
	[00042] = {{"@Garden of Madness/Underground Room/"}},
	[00043] = {{"@Garden of Madness/East Alcove/"}},

	[00044] = {{"@Demon Guest House/Secret Room/"}},
	[00045] = {{"@Demon Guest House/Antechamber/"}},
	[00046] = {{"@Demon Guest House/Lower Main Chamber Bottom Room/"}},
	[00047] = {{"@Demon Guest House/Puppet Hole/"}},
	[00048] = {{"@Demon Guest House/Number 1 Room/"}},
	[00049] = {{"@Demon Guest House/Number 5 Room/"}},
	[00050] = {{"@Demon Guest House/Number 8 Room/"}},
	[00051] = {{"@Demon Guest House/Number 9 Room/"}},
	[00052] = {{"@Demon Guest House/Number 12 Room/"}},
	[00053] = {{"@Demon Guest House/Mirror World/"}},
	[00054] = {{"@Demon Guest House/Mirror Room/"}},
	[00055] = {{"@Demon Guest House/Doll Alcove/"}},
	[00056] = {{"@Demon Guest House/West Wing Left/"}},
	[00057] = {{"@Demon Guest House/West Wing Right/"}},
	[00058] = {{"@Demon Guest House/Puppet Master Soul/"}},
	[00059] = {{"@Demon Guest House/Ice Block Room Left/"}},
	[00060] = {{"@Demon Guest House/Ice Block Room Right/"}},
	[00061] = {{"@Demon Guest House/Central Main Chamber Bottom Room/"}},
	[00062] = {{"@Demon Guest House/Central Main Chamber Middle Room/"}},
	[00063] = {{"@Demon Guest House/Central Main Chamber Top Room/"}},
	[00064] = {{"@Demon Guest House/Paranoia Soul/"}},
	[00065] = {{"@Demon Guest House/Beyond Paranoia/"}},
	[00066] = {{"@Demon Guest House/Paranoia Mirror/"}},

	[00067] = {{"@The Dark Chapel/Entrance Alcove/"}},
	[00068] = {{"@The Dark Chapel/Catacombs Top Left/"}},
	[00069] = {{"@The Dark Chapel/Catacombs Middle Room/"}},
	[00070] = {{"@The Dark Chapel/Catacombs Soul Barrier/"}},
	[00071] = {{"@The Dark Chapel/Catacombs Mirror Room/"}},
	[00072] = {{"@The Dark Chapel/Catacombs Mirror World/"}},
	[00073] = {{"@The Dark Chapel/Big Square Room Alcove/"}},
	[00074] = {{"@The Dark Chapel/Main Room/"}},
	[00075] = {{"@The Dark Chapel/Bell Room In Bell/"}},
	[00076] = {{"@The Dark Chapel/Bell Room Top Left/"}},
	[00077] = {{"@The Dark Chapel/Bell Room Right/"}},
	[00096] = {{"@The Dark Chapel/Post-Dimitrii Room/"}},
	[00097] = {{"@The Dark Chapel/Malphas Soul/"}},
	[00078] = {{"@The Dark Chapel/Big Room Top Right/"}},
	[00079] = {{"@The Dark Chapel/Big Room Central/"}},
	[00080] = {{"@The Dark Chapel/Big Room Lower/"}},

	[00081] = {{"@Condemned Tower/1F West/"}},
	[00082] = {{"@Condemned Tower/1F East/"}},
	[00083] = {{"@Condemned Tower/2F East/"}},
	[00084] = {{"@Condemned Tower/5F West/"}},
	[00085] = {{"@Condemned Tower/7F West/"}},
	[00086] = {{"@Condemned Tower/Top of the Tower/"}},
	[00087] = {{"@Condemned Tower/Gergoth Soul/"}},

	[00088] = {{"@Cursed Clock Tower/Money Gate/"}},
	[00089] = {{"@Cursed Clock Tower/Lower Corner Room/"}},
	[00090] = {{"@Cursed Clock Tower/Mirror Room/"}},
	[00091] = {{"@Cursed Clock Tower/Mirror World/"}},
	[00092] = {{"@Cursed Clock Tower/Bugbear Hallway/"}},
	[00093] = {{"@Cursed Clock Tower/East Gear Room/"}},
	[00094] = {{"@Cursed Clock Tower/Spike Room Secret/"}},
	[00095] = {{"@Cursed Clock Tower/Zephyr Soul/"}},

	[00098] = {{"@Subterranean Hell/Rahab Soul/"}},
	[00099] = {{"@Subterranean Hell/Giant Underwater Room Center Left/"}},
	[00100] = {{"@Subterranean Hell/Giant Underwater Room Center Right/"}},
	[00101] = {{"@Subterranean Hell/Giant Underwater Room Top Left/"}},
	[00102] = {{"@Subterranean Hell/Giant Underwater Room Bottom Right/"}},
	[00103] = {{"@Subterranean Hell/Near Save Room/"}},
	[00104] = {{"@Subterranean Hell/Central Lower Room/"}},
	[00105] = {{"@Subterranean Hell/Central Upper Room/"}},
	[00106] = {{"@Subterranean Hell/Behind Waterfall/"}},
	[00107] = {{"@Subterranean Hell/Waterfall Room Lower/"}},
	[00108] = {{"@Subterranean Hell/Waterfall Room Middle/"}},
	[00109] = {{"@Subterranean Hell/Waterfall Room Upper/"}},

	[00110] = {{"@Silenced Ruins/Ice Block Room/"}},
	[00111] = {{"@Silenced Ruins/Bat Company Soul/"}},
	[00112] = {{"@Silenced Ruins/Mirror Room/"}},
	[00113] = {{"@Silenced Ruins/Mirror World/"}},

	[00114] = {{"@The Pinnacle/Lower Hidden Room/"}},
	[00115] = {{"@The Pinnacle/Under Big Staircase/"}},
	[00116] = {{"@The Pinnacle/Central Indoor Room/"}},
	[00117] = {{"@The Pinnacle/Central Outdoor Room/"}},
	[00118] = {{"@The Pinnacle/Before Throne Room Secret Left/"}},
	[00119] = {{"@The Pinnacle/Before Throne Room Secret Right/"}},
	[00120] = {{"@The Pinnacle/Beyond Throne Room/"}},
	[00121] = {{"@The Pinnacle/Aguni Soul/"}},

	[00122] = {{"@Mine of Judgment/Death Soul/"}},

	[00123] = {{"@The Abyss/Sand Area/"}},
	[00124] = {{"@The Abyss/Ice Area/"}},
	[00125] = {{"@The Abyss/Abaddon Soul/"}}
}
