SOULSBYREGIONCODES = {
    {"@Soulsanity Front End (Regions)/The Lost Village Souls/The Lost Village - Upper/Yeti Soul"},
    {"@Soulsanity Front End (Regions)/The Lost Village Souls/The Lost Village - Upper/Axe Armor Soul"},
    {"@Soulsanity Front End (Regions)/The Lost Village Souls/The Lost Village - Upper/Warg Soul"},
    {"@Soulsanity Front End (Regions)/The Lost Village Souls/The Lost Village - Upper/Spin Devil Soul"},
    {"@Soulsanity Front End (Regions)/The Lost Village Souls/The Lost Village - Upper/Skeleton Soul"},
    {"@Soulsanity Front End (Regions)/The Lost Village Souls/The Lost Village - Upper/Bat Soul"},
    {"@Soulsanity Front End (Regions)/The Lost Village Souls/The Lost Village - Upper/Armor Knight Soul"},
    {"@Soulsanity Front End (Regions)/The Lost Village Souls/The Lost Village - Upper/Zombie Soul"},
    {"@Soulsanity Front End (Regions)/The Lost Village Souls/The Lost Village - Upper/Peeping Eye Soul"},
    {"@Soulsanity Front End (Regions)/The Lost Village Souls/The Lost Village - Upper Doorway/Skelerang Soul"},
    {"@Soulsanity Front End (Regions)/The Lost Village Souls/The Lost Village - Upper Doorway/Peeping Eye Soul"},
    {"@Soulsanity Front End (Regions)/The Lost Village Souls/The Lost Village - Courtyard/Warg Soul"},
    {"@Soulsanity Front End (Regions)/The Lost Village Souls/The Lost Village - Courtyard/Hell Boar Soul"},
    {"@Soulsanity Front End (Regions)/The Lost Village Souls/The Lost Village - Courtyard/Skeleton Ape Soul"},
    {"@Soulsanity Front End (Regions)/The Lost Village Souls/The Lost Village - Lower/Spin Devil Soul"},
    {"@Soulsanity Front End (Regions)/The Lost Village Souls/The Lost Village - Lower/Skeleton Soul"},
    {"@Soulsanity Front End (Regions)/The Lost Village Souls/The Lost Village - Lower/Armor Knight Soul"},
    {"@Soulsanity Front End (Regions)/The Lost Village Souls/The Lost Village - Lower/Bat Soul"},
    {"@Soulsanity Front End (Regions)/The Lost Village Souls/The Lost Village - Lower/Zombie Soul"},
    {"@Soulsanity Front End (Regions)/The Lost Village Souls/The Lost Village - Lower/Student Witch Soul"},
    {"@Soulsanity Front End (Regions)/The Lost Village Souls/The Lost Village - Lower/Ouija Table Soul"},
    {"@Soulsanity Front End (Regions)/The Lost Village Souls/The Lost Village - Underground Top/Axe Armor Soul"},
    {"@Soulsanity Front End (Regions)/The Lost Village Souls/The Lost Village - Underground Top/Merman Soul"},
    {"@Soulsanity Front End (Regions)/The Lost Village Souls/The Lost Village - Underground Top/Great Axe Armor Soul"},
    {"@Soulsanity Front End (Regions)/The Lost Village Souls/The Lost Village - Underground Bottom/White Dragon Soul"},
    {"@Soulsanity Front End (Regions)/Wizardry Lab Souls/Wizardry Lab - Main/Slime Soul"},
    {"@Soulsanity Front End (Regions)/Wizardry Lab Souls/Wizardry Lab - Main/Axe Armor Soul"},
    {"@Soulsanity Front End (Regions)/Wizardry Lab Souls/Wizardry Lab - Main/Bomber Armor Soul"},
    {"@Soulsanity Front End (Regions)/Wizardry Lab Souls/Wizardry Lab - Main/Student Witch Soul"},
    {"@Soulsanity Front End (Regions)/Wizardry Lab Souls/Wizardry Lab - Main/Skull Archer Soul"},
    {"@Soulsanity Front End (Regions)/Wizardry Lab Souls/Wizardry Lab - Main/Skeleton Soul"},
    {"@Soulsanity Front End (Regions)/Wizardry Lab Souls/Wizardry Lab - Main/Slaughterer Soul"},
    {"@Soulsanity Front End (Regions)/Wizardry Lab Souls/Wizardry Lab - Main/Manticore Soul"},
    {"@Soulsanity Front End (Regions)/Wizardry Lab Souls/Wizardry Lab - Main/Armor Knight Soul"},
    {"@Soulsanity Front End (Regions)/Wizardry Lab Souls/Wizardry Lab - Main/Golem Soul"},
    {"@Soulsanity Front End (Regions)/Wizardry Lab Souls/Wizardry Lab - Main/Ghost Soul"},
    {"@Soulsanity Front End (Regions)/Wizardry Lab Souls/Wizardry Lab - Main/The Creature Soul"},
    {"@Soulsanity Front End (Regions)/Wizardry Lab Souls/Wizardry Lab - West Gate/Great Axe Armor Soul"},
    {"@Soulsanity Front End (Regions)/Wizardry Lab Souls/Wizardry Lab - West Gate/Heart Eater Soul"},
    {"@Soulsanity Front End (Regions)/Wizardry Lab Souls/Wizardry Lab - East Gate/Cave Troll Soul"},
    {"@Soulsanity Front End (Regions)/Wizardry Lab Souls/Wizardry Lab - East Gate/Mimic Soul"},
    {"@Soulsanity Front End (Regions)/Wizardry Lab Souls/Wizardry Lab - Sunken/Homunculus Soul"},
    {"@Soulsanity Front End (Regions)/Wizardry Lab Souls/Wizardry Lab - Sunken/Larva Soul"},
    {"@Soulsanity Front End (Regions)/Wizardry Lab Souls/Wizardry Lab - Sunken West Door/Iron Golem Soul"},
    {"@Soulsanity Front End (Regions)/Wizardry Lab Souls/Wizardry Lab - Sunken West Door/Ghost Soul"},
    {"@Soulsanity Front End (Regions)/Garden of Madness Souls/Garden of Madness - Lower/Corpseweed Soul"},
    {"@Soulsanity Front End (Regions)/Garden of Madness Souls/Garden of Madness - Lower/Une Soul"},
    {"@Soulsanity Front End (Regions)/Garden of Madness Souls/Garden of Madness - Lower/Skelerang Soul"},
    {"@Soulsanity Front End (Regions)/Garden of Madness Souls/Garden of Madness - Lower/Mandragora Soul"},
    {"@Soulsanity Front End (Regions)/Garden of Madness Souls/Garden of Madness - Lower/Catoblepas Soul"},
    {"@Soulsanity Front End (Regions)/Garden of Madness Souls/Garden of Madness - Lower/Mollusca Soul"},
    {"@Soulsanity Front End (Regions)/Garden of Madness Souls/Garden of Madness - Lower/Yorick Soul"},
    {"@Soulsanity Front End (Regions)/Garden of Madness Souls/Garden of Madness - Lower/Rycuda Soul"},
    {"@Soulsanity Front End (Regions)/Garden of Madness Souls/Garden of Madness - Lower/Treant Soul"},
    {"@Soulsanity Front End (Regions)/Garden of Madness Souls/Garden of Madness - Lower/Skeleton Ape Soul"},
    {"@Soulsanity Front End (Regions)/Garden of Madness Souls/Garden of Madness - Lower/Skeleton Farmer Soul"},
    {"@Soulsanity Front End (Regions)/Garden of Madness Souls/Garden of Madness - Lower/Mimic Soul"},
    {"@Soulsanity Front End (Regions)/Garden of Madness Souls/Garden of Madness - Upper/Corpseweed Soul"},
    {"@Soulsanity Front End (Regions)/Garden of Madness Souls/Garden of Madness - Upper/Rycuda Soul"},
    {"@Soulsanity Front End (Regions)/Garden of Madness Souls/Garden of Madness - Upper/Mollusca Soul"},
    {"@Soulsanity Front End (Regions)/Garden of Madness Souls/Garden of Madness - Upper/Barbariccia Soul"},
    {"@Soulsanity Front End (Regions)/Garden of Madness Souls/Garden of Madness - Upper/Skeleton Ape Soul"},
    {"@Soulsanity Front End (Regions)/Garden of Madness Souls/Garden of Madness - Upper/Treant Soul"},
    {"@Soulsanity Front End (Regions)/Garden of Madness Souls/Garden of Madness - Post-Boss/Corpseweed Soul"},
    {"@Soulsanity Front End (Regions)/Garden of Madness Souls/Garden of Madness - Post-Boss/Skelerang Soul"},
    {"@Soulsanity Front End (Regions)/Garden of Madness Souls/Garden of Madness - Post-Boss/Une Soul"},
    {"@Soulsanity Front End (Regions)/Garden of Madness Souls/Garden of Madness - Post-Boss/Skeleton Ape Soul"},
    {"@Soulsanity Front End (Regions)/Garden of Madness Souls/Garden of Madness - Post-Boss/Ghoul Soul"},
    {"@Soulsanity Front End (Regions)/Garden of Madness Souls/Garden of Madness - East Gate/Wakwak Tree Soul"},
    {"@Soulsanity Front End (Regions)/The Dark Chapel Souls/The Dark Chapel - Main/Guillotiner Soul"},
    {"@Soulsanity Front End (Regions)/The Dark Chapel Souls/The Dark Chapel - Main/Witch Soul"},
    {"@Soulsanity Front End (Regions)/The Dark Chapel Souls/The Dark Chapel - Main/Mini Devil Soul"},
    {"@Soulsanity Front End (Regions)/The Dark Chapel Souls/The Dark Chapel - Main/Amalaric Sniper Soul"},
    {"@Soulsanity Front End (Regions)/The Dark Chapel Souls/The Dark Chapel - Main/Ghost Dancer Soul"},
    {"@Soulsanity Front End (Regions)/The Dark Chapel Souls/The Dark Chapel - Main/Hell Boar Soul"},
    {"@Soulsanity Front End (Regions)/The Dark Chapel Souls/The Dark Chapel - Main/White Dragon Soul"},
    {"@Soulsanity Front End (Regions)/The Dark Chapel Souls/The Dark Chapel - Main/Great Armor Soul"},
    {"@Soulsanity Front End (Regions)/The Dark Chapel Souls/The Dark Chapel - Main/Quetzalcoatl Soul"},
    {"@Soulsanity Front End (Regions)/The Dark Chapel Souls/The Dark Chapel - Main/Ghoul Soul"},
    {"@Soulsanity Front End (Regions)/The Dark Chapel Souls/The Dark Chapel - Main/The Creature Soul"},
    {"@Soulsanity Front End (Regions)/The Dark Chapel Souls/The Dark Chapel - Main/Bone Pillar Soul"},
    {"@Soulsanity Front End (Regions)/The Dark Chapel Souls/The Dark Chapel - Main/Barbariccia Soul"},
    {"@Soulsanity Front End (Regions)/The Dark Chapel Souls/The Dark Chapel - Main/Valkyrie Soul"},
    {"@Soulsanity Front End (Regions)/The Dark Chapel Souls/The Dark Chapel - Main/Ghost Soul"},
    {"@Soulsanity Front End (Regions)/The Dark Chapel Souls/The Dark Chapel - Main/Tombstone Soul"},
    {"@Soulsanity Front End (Regions)/The Dark Chapel Souls/The Dark Chapel - Big Room/Mini Devil Soul"},
    {"@Soulsanity Front End (Regions)/The Dark Chapel Souls/The Dark Chapel - Big Room/Quetzalcoatl Soul"},
    {"@Soulsanity Front End (Regions)/The Dark Chapel Souls/The Dark Chapel - Big Room/Valkyrie Soul"},
    {"@Soulsanity Front End (Regions)/The Dark Chapel Souls/The Dark Chapel - Catacombs Exit/Catoblepas Soul"},
    {"@Soulsanity Front End (Regions)/Demon Guest House Souls/Demon Guest House - Lower/Axe Armor Soul"},
    {"@Soulsanity Front End (Regions)/Demon Guest House Souls/Demon Guest House - Lower/Skeleton Soul"},
    {"@Soulsanity Front End (Regions)/Demon Guest House Souls/Demon Guest House - Lower/Peeping Eye Soul"},
    {"@Soulsanity Front End (Regions)/Demon Guest House Souls/Demon Guest House - Number Puzzle West/Persephone Soul"},
    {"@Soulsanity Front End (Regions)/Demon Guest House Souls/Demon Guest House - Puppet Wall Right/Skelerang Soul"},
    {"@Soulsanity Front End (Regions)/Demon Guest House Souls/Demon Guest House - Main/Persephone Soul"},
    {"@Soulsanity Front End (Regions)/Demon Guest House Souls/Demon Guest House - Main/Skelerang Soul"},
    {"@Soulsanity Front End (Regions)/Demon Guest House Souls/Demon Guest House - Main/Devil Soul"},
    {"@Soulsanity Front End (Regions)/Demon Guest House Souls/Demon Guest House - Main/Lilith Soul"},
    {"@Soulsanity Front End (Regions)/Demon Guest House Souls/Demon Guest House - Main/Ghost Dancer Soul"},
    {"@Soulsanity Front End (Regions)/Demon Guest House Souls/Demon Guest House - Main/Killer Clown Soul"},
    {"@Soulsanity Front End (Regions)/Demon Guest House Souls/Demon Guest House - Main/Waiter Skeleton Soul"},
    {"@Soulsanity Front End (Regions)/Demon Guest House Souls/Demon Guest House - Main/Valkyrie Soul"},
    {"@Soulsanity Front End (Regions)/Demon Guest House Souls/Demon Guest House - Main/Killer Doll Soul"},
    {"@Soulsanity Front End (Regions)/Demon Guest House Souls/Demon Guest House - Main/Bone Pillar Soul"},
    {"@Soulsanity Front End (Regions)/Demon Guest House Souls/Demon Guest House - West Wing/Buer Soul"},
    {"@Soulsanity Front End (Regions)/Demon Guest House Souls/Demon Guest House - West Wing/Killer Clown Soul"},
    {"@Soulsanity Front End (Regions)/Demon Guest House Souls/Demon Guest House - West Wing/Lilith Soul"},
    {"@Soulsanity Front End (Regions)/Demon Guest House Souls/Demon Guest House - West Wing/Quetzalcoatl Soul"},
    {"@Soulsanity Front End (Regions)/Demon Guest House Souls/Demon Guest House - West Wing/Killer Doll Soul"},
    {"@Soulsanity Front End (Regions)/Demon Guest House Souls/Demon Guest House - West Wing/Bone Pillar Soul"},
    {"@Soulsanity Front End (Regions)/Demon Guest House Souls/Demon Guest House - Upper/Flame Demon Soul"},
    {"@Soulsanity Front End (Regions)/Demon Guest House Souls/Demon Guest House - Upper/Malachi Soul"},
    {"@Soulsanity Front End (Regions)/Demon Guest House Souls/Demon Guest House - Upper/Skelerang Soul"},
    {"@Soulsanity Front End (Regions)/Demon Guest House Souls/Demon Guest House - Upper/Werewolf Soul"},
    {"@Soulsanity Front End (Regions)/Demon Guest House Souls/Demon Guest House - Upper/Ghost Dancer Soul"},
    {"@Soulsanity Front End (Regions)/Demon Guest House Souls/Demon Guest House - Upper/Student Witch Soul"},
    {"@Soulsanity Front End (Regions)/Demon Guest House Souls/Demon Guest House - Upper/Lilith Soul"},
    {"@Soulsanity Front End (Regions)/Demon Guest House Souls/Demon Guest House - Upper/Witch Soul"},
    {"@Soulsanity Front End (Regions)/Demon Guest House Souls/Demon Guest House - Upper/Succubus Soul"},
    {"@Soulsanity Front End (Regions)/Demon Guest House Souls/Demon Guest House - Upper/Persephone Soul"},
    {"@Soulsanity Front End (Regions)/Demon Guest House Souls/Demon Guest House - Upper/Iron Golem Soul"},
    {"@Soulsanity Front End (Regions)/Demon Guest House Souls/Demon Guest House - Upper/Mimic Soul"},
    {"@Soulsanity Front End (Regions)/Condemned Tower Souls/Condemned Tower - Bottom/Draghignazzo Soul"},
    {"@Soulsanity Front End (Regions)/Condemned Tower Souls/Condemned Tower - Top/Buer Soul"},
    {"@Soulsanity Front End (Regions)/Condemned Tower Souls/Condemned Tower - Top/Disc Armor Soul"},
    {"@Soulsanity Front End (Regions)/Condemned Tower Souls/Condemned Tower - Top/Werewolf Soul"},
    {"@Soulsanity Front End (Regions)/Condemned Tower Souls/Condemned Tower - Top/Fleaman Soul"},
    {"@Soulsanity Front End (Regions)/Condemned Tower Souls/Condemned Tower - Top/Skeleton Ape Soul"},
    {"@Soulsanity Front End (Regions)/Condemned Tower Souls/Condemned Tower - Top/Great Axe Armor Soul"},
    {"@Soulsanity Front End (Regions)/Subterrranean Hell Souls/Subterranean Hell - Top Entrance/Cave Troll Soul"},
    {"@Soulsanity Front End (Regions)/Subterrranean Hell Souls/Subterranean Hell - Top Entrance/Decarabia Soul"},
    {"@Soulsanity Front End (Regions)/Subterrranean Hell Souls/Subterranean Hell - Top Entrance/Une Soul"},
    {"@Soulsanity Front End (Regions)/Subterrranean Hell Souls/Subterranean Hell - Top Entrance/Dead Pirate Soul"},
    {"@Soulsanity Front End (Regions)/Subterrranean Hell Souls/Subterranean Hell - East/Decarabia Soul"},
    {"@Soulsanity Front End (Regions)/Subterrranean Hell Souls/Subterranean Hell - East/Merman Soul"},
    {"@Soulsanity Front End (Regions)/Subterrranean Hell Souls/Subterranean Hell - East/Fish Head Soul"},
    {"@Soulsanity Front End (Regions)/Subterrranean Hell Souls/Subterranean Hell - East/Needles Soul"},
    {"@Soulsanity Front End (Regions)/Subterrranean Hell Souls/Subterranean Hell - East/Frozen Shade Soul"},
    {"@Soulsanity Front End (Regions)/Subterrranean Hell Souls/Subterranean Hell - East/Killer Fish Soul"},
    {"@Soulsanity Front End (Regions)/Subterrranean Hell Souls/Subterranean Hell - East/Mimic Soul"},
    {"@Soulsanity Front End (Regions)/Subterrranean Hell Souls/Subterranean Hell - East/Procel Soul"},
    {"@Soulsanity Front End (Regions)/Subterrranean Hell Souls/Subterranean Hell - Central/East Connection/Une Soul"},
    {"@Soulsanity Front End (Regions)/Subterrranean Hell Souls/Subterranean Hell - Central/East Connection/Alura Une Soul"},
    {"@Soulsanity Front End (Regions)/Subterrranean Hell Souls/Subterranean Hell - Central Upper/Merman Soul"},
    {"@Soulsanity Front End (Regions)/Subterrranean Hell Souls/Subterranean Hell - Central Upper/Ukoback Soul"},
    {"@Soulsanity Front End (Regions)/Subterrranean Hell Souls/Subterranean Hell - Central Upper/Frozen Shade Soul"},
    {"@Soulsanity Front End (Regions)/Subterrranean Hell Souls/Subterranean Hell - Central Upper/Dead Pirate Soul"},
    {"@Soulsanity Front End (Regions)/Subterrranean Hell Souls/Subterranean Hell - Central Upper/Killer Fish Soul"},
    {"@Soulsanity Front End (Regions)/Subterrranean Hell Souls/Subterranean Hell - Central Upper/Needles Soul"},
    {"@Soulsanity Front End (Regions)/Subterrranean Hell Souls/Subterranean Hell - Central Upper/Bone Ark Soul"},
    {"@Soulsanity Front End (Regions)/Subterrranean Hell Souls/Subterranean Hell - Central Lower/Merman Soul"},
    {"@Soulsanity Front End (Regions)/Subterrranean Hell Souls/Subterranean Hell - Central Lower/Frozen Shade Soul"},
    {"@Soulsanity Front End (Regions)/Subterrranean Hell Souls/Subterranean Hell - Central Lower/Dead Pirate Soul"},
    {"@Soulsanity Front End (Regions)/Subterrranean Hell Souls/Subterranean Hell - Central Lower/Procel Soul"},
    {"@Soulsanity Front End (Regions)/Subterrranean Hell Souls/Subterranean Hell - Central Exit/Merman Soul"},
    {"@Soulsanity Front End (Regions)/Subterrranean Hell Souls/Subterranean Hell - Central Exit/Ukoback Soul"},
    {"@Soulsanity Front End (Regions)/Subterrranean Hell Souls/Subterranean Hell - Central Exit/Frozen Shade Soul"},
    {"@Soulsanity Front End (Regions)/Subterrranean Hell Souls/Subterranean Hell - Central Exit/Mimic Soul"},
    {"@Soulsanity Front End (Regions)/Subterrranean Hell Souls/Subterranean Hell - Shaft Bottom/Merman Soul"},
    {"@Soulsanity Front End (Regions)/Subterrranean Hell Souls/Subterranean Hell - Shaft Bottom/Dead Pirate Soul"},
    {"@Soulsanity Front End (Regions)/Subterrranean Hell Souls/Subterranean Hell - Shaft Bottom/Ukoback Soul"},
    {"@Soulsanity Front End (Regions)/Subterrranean Hell Souls/Subterranean Hell - Shaft Bottom/Medusa Head Soul"},
    {"@Soulsanity Front End (Regions)/Subterrranean Hell Souls/Subterranean Hell - Shaft Middle/Merman Soul"},
    {"@Soulsanity Front End (Regions)/Subterrranean Hell Souls/Subterranean Hell - Shaft Middle/Frozen Shade Soul"},
    {"@Soulsanity Front End (Regions)/Subterrranean Hell Souls/Subterranean Hell - Shaft Middle/Devil Soul"},
    {"@Soulsanity Front End (Regions)/Subterrranean Hell Souls/Subterranean Hell - Shaft Top/Killer Fish Soul"},
    {"@Soulsanity Front End (Regions)/Subterrranean Hell Souls/Subterranean Hell - Shaft Top/Ukoback Soul"},
    {"@Soulsanity Front End (Regions)/Cursed Clock Tower Souls/Cursed Clock Tower - Entrance/Harpy Soul"},
    {"@Soulsanity Front End (Regions)/Cursed Clock Tower Souls/Cursed Clock Tower - Entrance/Catoblepas Soul"},
    {"@Soulsanity Front End (Regions)/Cursed Clock Tower Souls/Cursed Clock Tower - Entrance/Imp Soul"},
    {"@Soulsanity Front End (Regions)/Cursed Clock Tower Souls/Cursed Clock Tower - Entrance/Malachi Soul"},
    {"@Soulsanity Front End (Regions)/Cursed Clock Tower Souls/Cursed Clock Tower - Entrance/Dead Pirate Soul"},
    {"@Soulsanity Front End (Regions)/Cursed Clock Tower Souls/Cursed Clock Tower - Entrance/Medusa Head Soul"},
    {"@Soulsanity Front End (Regions)/Cursed Clock Tower Souls/Cursed Clock Tower - Entrance/Tanjelly Soul"},
    {"@Soulsanity Front End (Regions)/Cursed Clock Tower Souls/Cursed Clock Tower - Central/Slime Soul"},
    {"@Soulsanity Front End (Regions)/Cursed Clock Tower Souls/Cursed Clock Tower - Central/Imp Soul"},
    {"@Soulsanity Front End (Regions)/Cursed Clock Tower Souls/Cursed Clock Tower - Central/Medusa Head Soul"},
    {"@Soulsanity Front End (Regions)/Cursed Clock Tower Souls/Cursed Clock Tower - Central/Bugbear Soul"},
    {"@Soulsanity Front End (Regions)/Cursed Clock Tower Souls/Cursed Clock Tower - Central/Tanjelly Soul"},
    {"@Soulsanity Front End (Regions)/Cursed Clock Tower Souls/Cursed Clock Tower - Boss Area/Flying Humanoid Soul"},
    {"@Soulsanity Front End (Regions)/Cursed Clock Tower Souls/Cursed Clock Tower - Exit/Devil Soul"},
    {"@Soulsanity Front End (Regions)/Cursed Clock Tower Souls/Cursed Clock Tower - Exit/Harpy Soul"},
    {"@Soulsanity Front End (Regions)/Silenced Ruins Souls/Silenced Ruins - Main/Dead Mate Soul"},
    {"@Soulsanity Front End (Regions)/Silenced Ruins Souls/Silenced Ruins - Main/Bat Soul"},
    {"@Soulsanity Front End (Regions)/Silenced Ruins Souls/Silenced Ruins - Main/Skull Archer Soul"},
    {"@Soulsanity Front End (Regions)/Silenced Ruins Souls/Silenced Ruins - Main/Devil Soul"},
    {"@Soulsanity Front End (Regions)/Silenced Ruins Souls/Silenced Ruins - Main/Larva Soul"},
    {"@Soulsanity Front End (Regions)/Silenced Ruins Souls/Silenced Ruins - Main/Ghoul Soul"},
    {"@Soulsanity Front End (Regions)/Silenced Ruins Souls/Silenced Ruins - Main/Peeping Eye Soul"},
    {"@Soulsanity Front End (Regions)/Silenced Ruins Souls/Silenced Ruins - Main/Dead Crusader Soul"},
    {"@Soulsanity Front End (Regions)/Silenced Ruins Souls/Silenced Ruins - Main/Bone Ark Soul"},
    {"@Soulsanity Front End (Regions)/Silenced Ruins Souls/Silenced Ruins - Upper Entrance/Waiter Skeleton Soul"},
    {"@Soulsanity Front End (Regions)/Silenced Ruins Souls/Silenced Ruins - Upper Entrance/Gorgon Soul"},
    {"@Soulsanity Front End (Regions)/Silenced Ruins Souls/Silenced Ruins - Upper Entrance/Peeping Eye Soul"},
    {"@Soulsanity Front End (Regions)/Silenced Ruins Souls/Silenced Ruins - Back Exit/Waiter Skeleton Soul"},
    {"@Soulsanity Front End (Regions)/The Pinnacle Souls/The Pinnacle - Main/Guillotiner Soul"},
    {"@Soulsanity Front End (Regions)/The Pinnacle Souls/The Pinnacle - Main/Mothman Soul"},
    {"@Soulsanity Front End (Regions)/The Pinnacle Souls/The Pinnacle - Main/Werewolf Soul"},
    {"@Soulsanity Front End (Regions)/The Pinnacle Souls/The Pinnacle - Main/Mushussu Soul"},
    {"@Soulsanity Front End (Regions)/The Pinnacle Souls/The Pinnacle - Main/Alastor Soul"},
    {"@Soulsanity Front End (Regions)/The Pinnacle Souls/The Pinnacle - Main/Dead Crusader Soul"},
    {"@Soulsanity Front End (Regions)/The Pinnacle Souls/The Pinnacle - Main/Erinys Soul"},
    {"@Soulsanity Front End (Regions)/The Pinnacle Souls/The Pinnacle - Main/Final Guard Soul"},
    {"@Soulsanity Front End (Regions)/The Pinnacle Souls/The Pinnacle - Lower/Guillotiner Soul"},
    {"@Soulsanity Front End (Regions)/The Pinnacle Souls/The Pinnacle - Lower/Succubus Soul"},
    {"@Soulsanity Front End (Regions)/The Pinnacle Souls/The Pinnacle - Lower/Malachi Soul"},
    {"@Soulsanity Front End (Regions)/The Pinnacle Souls/The Pinnacle - Lower/Mushussu Soul"},
    {"@Soulsanity Front End (Regions)/The Pinnacle Souls/The Pinnacle - Lower/Werewolf Soul"},
    {"@Soulsanity Front End (Regions)/The Pinnacle Souls/The Pinnacle - Lower/Flame Demon Soul"},
    {"@Soulsanity Front End (Regions)/The Pinnacle Souls/The Pinnacle - Lower/Bugbear Soul"},
    {"@Soulsanity Front End (Regions)/The Pinnacle Souls/The Pinnacle - Lower/Dead Warrior Soul"},
    {"@Soulsanity Front End (Regions)/The Pinnacle Souls/The Pinnacle - Lower/Erinys Soul"},
    {"@Soulsanity Front End (Regions)/Mine of Judgment Souls/Mine of Judgment/Slogra Soul"},
    {"@Soulsanity Front End (Regions)/Mine of Judgment Souls/Mine of Judgment/Ripper Soul"},
    {"@Soulsanity Front End (Regions)/Mine of Judgment Souls/Mine of Judgment/Gaibon Soul"},
    {"@Soulsanity Front End (Regions)/Mine of Judgment Souls/Mine of Judgment/Tanjelly Soul"},
    {"@Soulsanity Front End (Regions)/Mine of Judgment Souls/Mine of Judgment/Giant Slug Soul"},
    {"@Soulsanity Front End (Regions)/Mine of Judgment Souls/Mine of Judgment/Bugbear Soul"},
    {"@Soulsanity Front End (Regions)/The Abyss Souls/The Abyss - Before Abaddon/Alastor Soul"},
    {"@Soulsanity Front End (Regions)/The Abyss Souls/The Abyss - Before Abaddon/Mud Demon Soul"},
    {"@Soulsanity Front End (Regions)/The Abyss Souls/The Abyss - Before Abaddon/Frozen Shade Soul"},
    {"@Soulsanity Front End (Regions)/The Abyss Souls/The Abyss - Before Abaddon/Malachi Soul"},
    {"@Soulsanity Front End (Regions)/The Abyss Souls/The Abyss - Before Abaddon/White Dragon Soul"},
    {"@Soulsanity Front End (Regions)/The Abyss Souls/The Abyss - Before Abaddon/Malacoda Soul"},
    {"@Soulsanity Front End (Regions)/The Abyss Souls/The Abyss - Before Abaddon/Arc Demon Soul"},
    {"@Soulsanity Front End (Regions)/The Abyss Souls/The Abyss - Before Abaddon/Erinys Soul"},
    {"@Soulsanity Front End (Regions)/The Abyss Souls/The Abyss - Before Abaddon/Heart Eater Soul"},
    {"@Soulsanity Front End (Regions)/The Abyss Souls/The Abyss - Before Abaddon/Stolas Soul"},
    {"@Soulsanity Front End (Regions)/The Abyss Souls/The Abyss - Before Abaddon/Final Guard Soul"},
    {"@Soulsanity Front End (Regions)/The Abyss Souls/The Abyss - Beyond Abaddon/Black Panther Soul"},
    {"@Soulsanity Front End (Regions)/The Abyss Souls/The Abyss - Beyond Abaddon/Succubus Soul"},
    {"@Soulsanity Front End (Regions)/The Abyss Souls/The Abyss - Beyond Abaddon/Iron Golem Soul"},
}
